#!/usr/bin/env bash

docker compose -f docker-compose.yml -f docker-compose.dev.yml --env-file env-dev build --progress plain "$@" \
	&& docker compose -f docker-compose.yml -f docker-compose.dev.yml --env-file env-dev up "$@"
