#!/usr/bin/env bash

if [ "$1" = "reset" ]
then
  if [ ! -z "$(docker volume ls | grep desecstack_dbapi)" ]
  then
    echo "removing dbapi volume"
    docker volume rm desecstack_dbapi_mysql || \
        (
            echo "removing dbapi container"
            # remove container that has uses this volume
            CONTAINER="$(docker volume rm desecstack_dbapi_mysql |& egrep -o '[a-f0-9]{64}')"
            docker rm -f $CONTAINER
            echo "removing dbapi volume (2nd try)"
            docker volume rm desecstack_dbapi_mysql
        )
  fi
fi

if [ -z "$(docker volume ls | grep desecstack_dbapi)" ]
then
  echo "NO DBAPI FOUND, PREPARING DBAPI"
  docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.test.yml build dbapi
  docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.test.yml up -d dbapi
  sleep 60
fi &

if [ -z "$(docker volume ls | grep 'desecstack_dblord')" ]
then
  echo "NO NSLORD/NSMASTER FOUND, PREPARING"
  docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.test.yml build dblord nslord
  docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.test.yml up -d dblord
  sleep 60
  docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.test.yml up -d nslord
  sleep 10
fi &

wait

docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.test.yml build api
docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.test.yml up --abort-on-container-exit api

docker-compose ps

exit $(docker-compose ps -q | xargs docker inspect -f '{{ .State.ExitCode }}' | grep -v 0 | wc -l | tr -d ' ')

