# Generated by Django 3.1 on 2020-08-26 07:42

# It appears that this migration is "unsquashable". If you squash it in 0001, Django will think it's missing and
# generate it next time again.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0001_initial_squashed_again'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'managed': False},
        ),
    ]
