# Generated by Django 3.1 on 2020-08-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0002_unmanaged_donations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rr',
            name='content',
            field=models.TextField(),
        ),
    ]
