# Generated by Django 3.1 on 2020-08-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0003_rr_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='renewal_state',
            field=models.IntegerField(choices=[(0, 'Immortal'), (1, 'Fresh'), (2, 'Notified'), (3, 'Warned')], default=0),
        ),
    ]
