# Generated by Django 2.2.3 on 2019-07-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0003_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='minimum_ttl',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='rrset',
            name='ttl',
            field=models.PositiveIntegerField(),
        ),
    ]
