# Generated by Django 2.2.2 on 2019-06-28 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0004_domain_minimum_ttl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dyn',
        ),
        migrations.RemoveField(
            model_name='user',
            name='locked',
        ),
    ]
