# Generated by Django 3.1 on 2020-09-18 16:09

import django.contrib.postgres.constraints
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0005_subname_validation'),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.AddConstraint(
            model_name='rrset',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('domain', '='), ('subname', '='), (django.db.models.expressions.RawSQL("int4(type = 'CNAME')", ()), '<>')], name='cname_exclusivity'),
        ),
    ]
