# Generated by Django 2.2.1 on 2019-09-22 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0006_authenticated_actions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registration_remote_ip',
        ),
    ]
