# Generated by Django 2.2.1 on 2019-09-22 10:26

import desecapi.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0007_remove_user_registration_remote_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(default=desecapi.models.captcha_default_content, max_length=24)),
            ],
        ),
    ]
