# Generated by Django 3.1.2 on 2020-11-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0007_email_citext'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='perm_manage_tokens',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='perm_manage_tokens',
            field=models.BooleanField(default=False),
        ),
    ]
