# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0008_django_update_1-10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=191, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=191, unique=True, verbose_name='email address'),
        ),
    ]
