# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0008_django_update_1-10'),
    ]

    operations = [
        migrations.RunSQL(
            [('alter table desecapi_user change column email email varchar(191) not null;', None)],
            migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            [('alter table desecapi_domain change column name name varchar(191) not null;', None)],
            migrations.RunSQL.noop
        ),
    ]
