# Generated by Django 3.1.3 on 2020-11-05 19:19

import desecapi.models
import django.contrib.postgres.fields
from django.db import migrations
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0008_token_perm_manage_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='allowed_subnets',
            field=django.contrib.postgres.fields.ArrayField(base_field=netfields.fields.CidrAddressField(max_length=43), default=desecapi.models.Token._allowed_subnets_default, size=None),
        ),
    ]
