# Generated by Django 2.2.6 on 2019-10-10 15:07

import desecapi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0008_captcha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='minimum_ttl',
            field=models.PositiveIntegerField(default=desecapi.models.get_minimum_ttl_default),
        ),
    ]

