# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0009_auto_20161201_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='captcha_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_remote_ip',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
