# Generated by Django 2.2.7 on 2019-11-11 20:14

from django.contrib.auth.hashers import make_password
from django.db import migrations, models, transaction
import uuid


def migrate_data(apps, schema_editor):
    Token = apps.get_model('desecapi', 'Token')
    tokens = Token.objects.exclude(key__contains='$').all()
    with transaction.atomic():
        for token in tokens:
            hashed = make_password(token.key, salt='static', hasher='pbkdf2_sha256_iter1')
            Token.objects.filter(key=token.key).update(id=uuid.uuid4().hex, key=hashed)


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0009_domain_minimum_ttl_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'verbose_name': 'Token', 'verbose_name_plural': 'Tokens'},
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='token',
            name='user_specific_id',
        ),
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='token',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.RunPython(migrate_data, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='token',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
