# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-27 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0010_auto_20161219_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='limit_domains',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
