# Generated by Django 3.1.4 on 2020-12-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0010_token_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='captcha',
            name='kind',
            field=models.CharField(choices=[('image', 'Image'), ('audio', 'Audio')], default='image', max_length=24),
        ),
        migrations.AlterField(
            model_name='captcha',
            name='content',
            field=models.CharField(default='', max_length=24),
        ),
    ]
