# Generated by Django 2.2.7 on 2019-11-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0011_user_id_to_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'managed': False},
        ),
    ]
