# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0011_user_limit_domains'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='dyn',
        ),
        migrations.AddField(
            model_name='user',
            name='dyn',
            field=models.BooleanField(default=True),
        ),
    ]
