# Generated by Django 3.1.5 on 2021-01-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0012_rrset_label_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='needs_captcha',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='needs_captcha',
            field=models.BooleanField(default=True),
        ),
    ]
