# Generated by Django 3.0.5 on 2020-04-29 17:41

import desecapi.models
import django.core.validators
from django.db import migrations, models, transaction


def migrate_data(apps, schema_editor):
    Token = apps.get_model('desecapi', 'Token')
    tokens = Token.objects.filter(last_used__isnull=True).all()
    with transaction.atomic():
        for token in tokens:
            # Don't suggest that existing tokens have not been in use.
            Token.objects.filter(pk=token.id).update(last_used=token.user.last_login)


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0012_volatile_donations'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='name',
            field=models.CharField(blank=True, max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=191, unique=True, validators=[desecapi.models.validate_lower, django.core.validators.RegexValidator(code='invalid_domain_name', message='Invalid value (not a DNS name).', regex='^([a-z0-9_-]{1,63}\\.)*[a-z]{1,63}$')]),
        ),
        migrations.AlterField(
            model_name='rr',
            name='content',
            field=models.CharField(max_length=500),
        ),
        migrations.RunPython(migrate_data, migrations.RunPython.noop),
    ]
