# Generated by Django 3.0.6 on 2020-05-21 10:59

import desecapi.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0013_token_last_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rrset',
            old_name='updated',
            new_name='touched',
        ),
    ]
