# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0013_acme_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='aaaarecord',
            field=models.GenericIPAddressField(blank=False, null=True, protocol='IPv6'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='arecord',
            field=models.GenericIPAddressField(blank=False, null=True, protocol='IPv4'),
        ),
    ]
