# Generated by Django 3.0.6 on 2020-05-22 12:10

from django.db import migrations, models


def migrate_data(apps, schema_editor):
    RRset = apps.get_model('desecapi', 'RRset')
    RRset.objects.filter(touched__isnull=True).update(touched=models.F('created'))


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0014_rrset_touched'),
    ]

    operations = [
        migrations.RunPython(migrate_data, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='rrset',
            name='touched',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
