# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-28 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0015_rrset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dyn',
            field=models.BooleanField(default=False),
        ),
    ]
