# Generated by Django 3.1.5 on 2021-01-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0015_identities'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlsidentity',
            name='port',
            field=models.IntegerField(default=443),
        ),
        migrations.AddField(
            model_name='tlsidentity',
            name='protocol',
            field=models.TextField(choices=[('tcp', 'Tcp'), ('udp', 'Udp'), ('sctp', 'Sctp')], default='tcp'),
        ),
        migrations.AddField(
            model_name='tlsidentity',
            name='scheduled_removal',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tlsidentity',
            name='tlsa_certificate_usage',
            field=models.IntegerField(choices=[(0, 'Ca Constraint'), (1, 'Service Certificate Constraint'), (2, 'Trust Anchor Assertion'), (3, 'Domain Issued Certificate')], default=3),
        ),
        migrations.AddField(
            model_name='tlsidentity',
            name='tlsa_matching_type',
            field=models.IntegerField(choices=[(0, 'No Hash Used'), (1, 'Sha256'), (2, 'Sha512')], default=1),
        ),
        migrations.AddField(
            model_name='tlsidentity',
            name='tlsa_selector',
            field=models.IntegerField(choices=[(0, 'Full Certificate'), (1, 'Subject Public Key Info')], default=1),
        ),
    ]
