# Generated by Django 3.1.3 on 2020-11-23 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0015_rrset_touched_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TokenDomainPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perm_dyndns', models.BooleanField(default=False)),
                ('perm_other', models.BooleanField(default=False)),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='desecapi.domain')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desecapi.token')),
            ],
        ),
        migrations.AddField(
            model_name='token',
            name='domain_policies',
            field=models.ManyToManyField(through='desecapi.TokenDomainPolicy', to='desecapi.Domain'),
        ),
        migrations.AddConstraint(
            model_name='tokendomainpolicy',
            constraint=models.UniqueConstraint(fields=('token', 'domain'), name='unique_entry'),
        ),
        migrations.AddConstraint(
            model_name='tokendomainpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(domain__isnull=True), fields=('token',), name='unique_entry_null_domain'),
        ),
    ]
