# Generated by Django 3.0.6 on 2020-06-29 19:15

import desecapi.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0015_rrset_touched_auto_now'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticatedBasicUserAction',
            fields=[
                ('authenticatedaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='desecapi.AuthenticatedAction')),
            ],
            options={
                'managed': False,
            },
            bases=('desecapi.authenticatedaction',),
        ),
        migrations.AddField(
            model_name='domain',
            name='renewal_changed',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='renewal_state',
            field=models.IntegerField(choices=[(1, 'Fresh'), (2, 'Notified'), (3, 'Warned')], default=1),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=191, unique=True, validators=[desecapi.models.validate_lower, django.core.validators.RegexValidator(code='invalid_domain_name', flags=re.RegexFlag['IGNORECASE'], message='Domain names must be labels separated by dots. Labels may consist of up to 63 letters, digits, hyphens, and underscores. The last label may only contain letters.', regex='^(([a-z0-9_-]{1,63})\\.)*[a-z]{1,63}$')]),
        ),
        migrations.CreateModel(
            name='AuthenticatedDomainBasicUserAction',
            fields=[
                ('authenticatedbasicuseraction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='desecapi.AuthenticatedBasicUserAction')),
            ],
            options={
                'managed': False,
            },
            bases=('desecapi.authenticatedbasicuseraction',),
        ),
        migrations.CreateModel(
            name='AuthenticatedRenewDomainBasicUserAction',
            fields=[
                ('authenticateddomainbasicuseraction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='desecapi.AuthenticatedDomainBasicUserAction')),
            ],
            options={
                'managed': False,
            },
            bases=('desecapi.authenticateddomainbasicuseraction',),
        ),
    ]
