# Generated by Django 3.1.6 on 2021-02-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0016_identities'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlsidentity',
            name='default_ttl',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='tlsidentity',
            name='tlsa_certificate_usage',
            field=models.IntegerField(choices=[(0, 'Ca Constraint'), (1, 'Service Certificate Constraint'), (2, 'Trust Anchor Assertion'), (3, 'Domain Issued Certificate')], default=3),
        ),
        migrations.AlterField(
            model_name='tlsidentity',
            name='tlsa_matching_type',
            field=models.IntegerField(choices=[(0, 'No Hash Used'), (1, 'Sha256'), (2, 'Sha512')], default=1),
        ),
        migrations.AlterField(
            model_name='tlsidentity',
            name='tlsa_selector',
            field=models.IntegerField(choices=[(0, 'Full Certificate'), (1, 'Subject Public Key Info')], default=1),
        ),
    ]
