# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0016_dyn_flag_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='RR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=4092)),
            ],
        ),
        migrations.RemoveField(
            model_name='rrset',
            name='records',
        ),
        migrations.AlterField(
            model_name='rrset',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desecapi.Domain'),
        ),
        migrations.AddField(
            model_name='rr',
            name='rrset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='desecapi.RRset'),
        ),
    ]
