# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0017_rr_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='aaaarecord',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='acme_challenge',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='arecord',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='updated',
        ),
    ]
