# Generated by Django 3.2.7 on 2021-09-19 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0017_alter_user_limit_domains'),
    ]

    operations = [
        migrations.CreateModel(
            name='TLSIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=24)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('default_ttl', models.PositiveIntegerField(default=300)),
                ('scheduled_removal', models.DateTimeField(null=True)),
                ('certificate', models.TextField()),
                ('tlsa_selector', models.IntegerField(choices=[(0, 'Full Certificate'), (1, 'Subject Public Key Info')], default=1)),
                ('tlsa_matching_type', models.IntegerField(choices=[(0, 'No Hash Used'), (1, 'Sha256'), (2, 'Sha512')], default=1)),
                ('tlsa_certificate_usage', models.IntegerField(choices=[(0, 'Ca Constraint'), (1, 'Service Certificate Constraint'), (2, 'Trust Anchor Assertion'), (3, 'Domain Issued Certificate')], default=3)),
                ('port', models.IntegerField(default=443)),
                ('protocol', models.TextField(choices=[('tcp', 'Tcp'), ('udp', 'Udp'), ('sctp', 'Sctp')], default='tcp')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identities', to=settings.AUTH_USER_MODEL)),
                ('rrs', models.ManyToManyField(to='desecapi.RR')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
