# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0018_prune_domain_fields'),
    ]

    operations = [
        # This code is generated by manage.py sqlmigrate based on the below AlterField statement.
        # Unfortunately, a wrong SQL statement sneaks in when the migration is run in sequence
        # with all other migrations, causing an error. (To reproduce, start from a fresh database,
        # and observe the database query logs).
        # Applying all but this migration and then applying this migration works fine. To make
        # sure that the migration works in all scenarios, we manually enforce the SQL statements
        # that are run when the migration is applied alone. (As observed in database query log.)
        migrations.RunSQL(
            [
                "ALTER TABLE `desecapi_rr` DROP FOREIGN KEY `desecapi_rr_rrset_id_675bf73d_fk_desecapi_rrset_id`;",
                "ALTER TABLE `desecapi_rrset` MODIFY `id` char(32) NOT NULL;",
                "ALTER TABLE `desecapi_rrset` ALTER COLUMN `id` SET DEFAULT 'b748720af78149fdb17c2ee2f284262d';",
                "ALTER TABLE `desecapi_rr` MODIFY `rrset_id` char(32) NOT NULL;",
                "ALTER TABLE `desecapi_rr` ADD CONSTRAINT `desecapi_rr_rrset_id_675bf73d_fk` FOREIGN KEY (`rrset_id`) REFERENCES `desecapi_rrset` (`id`);",
                "ALTER TABLE `desecapi_rrset` ALTER COLUMN `id` DROP DEFAULT;",
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='rrset',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False,
                                           primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
