# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-15 19:01
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone


def forward_convert(apps, schema_editor):
    User = apps.get_model('desecapi', 'User')
    for user in User.objects.all().iterator():
        if user.captcha_required:
            user.locked = timezone.now()
            user.save()


def reverse_convert(apps, schema_editor):
    User = apps.get_model('desecapi', 'User')
    for user in User.objects.all().iterator():
        if user.locked:
            user.captcha_required = True
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0019_rrset_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='locked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(forward_convert, reverse_convert),
        migrations.RemoveField(
            model_name='user',
            name='captcha_required',
        ),
    ]
