# Generated by Django 4.0.1 on 2022-01-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0021_authenticatednoopuseraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='outreach_preference',
            field=models.BooleanField(default=True),
        ),
    ]
