# Generated by Django 4.0.1 on 2022-01-19 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("desecapi", "0022_user_outreach_preference"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthenticatedEmailUserAction",
            fields=[
                (
                    "authenticatedbasicuseraction_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="desecapi.authenticatedbasicuseraction",
                    ),
                ),
            ],
            options={
                "managed": False,
            },
            bases=("desecapi.authenticatedbasicuseraction",),
        ),
    ]
