# Generated by Django 4.0.6 on 2022-08-11 16:37

import datetime
import django.core.validators
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    max_interval = datetime.timedelta(days=365000)
    Token = apps.get_model("desecapi", "Token")
    db_alias = schema_editor.connection.alias
    Token.objects.using(db_alias).filter(max_age__gt=max_interval).update(max_age=max_interval)
    Token.objects.using(db_alias).filter(max_unused_period__gt=max_interval).update(max_unused_period=max_interval)


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0024_authenticatedchangeoutreachpreferenceuseraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='max_age',
            field=models.DurationField(default=None, null=True, validators=[django.core.validators.MinValueValidator(datetime.timedelta(0)), django.core.validators.MaxValueValidator(datetime.timedelta(days=365000))]),
        ),
        migrations.AlterField(
            model_name='token',
            name='max_unused_period',
            field=models.DurationField(default=None, null=True, validators=[django.core.validators.MinValueValidator(datetime.timedelta(0)), django.core.validators.MaxValueValidator(datetime.timedelta(days=365000))]),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
