# Generated by Django 4.1 on 2022-08-11 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0025_alter_token_max_age_alter_token_max_unused_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='replicated',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='replication_duration',
        ),
    ]
