# Generated by Django 4.2.7 on 2023-11-23 13:10

from django.db import migrations, models
import uuid


def forwards_func(apps, schema_editor):
    TokenDomainPolicy = apps.get_model("desecapi", "TokenDomainPolicy")
    db_alias = schema_editor.connection.alias
    for policy in TokenDomainPolicy.objects.using(db_alias).all():
        policy.id_uuid = uuid.uuid4()
        policy.save()


class Migration(migrations.Migration):
    dependencies = [
        ("desecapi", "0032_tokendomainpolicy_token_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokendomainpolicy",
            name="id_uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(forwards_func),
        migrations.AlterField(
            model_name="tokendomainpolicy",
            name="id_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, serialize=False),
        ),
        migrations.RemoveField(
            model_name="tokendomainpolicy",
            name="id",
        ),
        migrations.RenameField(
            model_name="tokendomainpolicy",
            old_name="id_uuid",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="tokendomainpolicy",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
