# Generated by Django 4.2.7 on 2023-11-23 13:58

import desecapi.models.base
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desecapi", "0033_alter_tokendomainpolicy_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokendomainpolicy",
            name="subname",
            field=models.CharField(
                blank=True,
                max_length=178,
                null=True,
                validators=[
                    desecapi.models.base.validate_lower,
                    django.core.validators.RegexValidator(
                        code="invalid_subname",
                        message="Subname can only use (lowercase) a-z, 0-9, ., -, and _, may start with a '*.', or just be '*'. Components may not exceed 63 characters.",
                        regex="^([*]|(([*][.])?([a-z0-9_-]{1,63}[.])*[a-z0-9_-]{1,63}))$",
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="tokendomainpolicy",
            name="type",
            field=models.CharField(
                max_length=10,
                null=True,
                validators=[
                    desecapi.models.base.validate_upper,
                    django.core.validators.RegexValidator(
                        code="invalid_type",
                        message="Type must be uppercase alphanumeric and start with a letter.",
                        regex="^[A-Z][A-Z0-9]*$",
                    ),
                ],
            ),
        ),
    ]
