# Generated by Django 5.0rc1 on 2023-12-01 17:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("desecapi", "0034_tokendomainpolicy_subname_tokendomainpolicy_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tokendomainpolicy",
            old_name="perm_rrsets",
            new_name="perm_write",
        ),
    ]
