# Generated by Django 5.0 on 2023-12-15 16:09

import django.db.models.deletion
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desecapi", "0037_remove_tokendomainpolicy_perm_dyndns"),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainSerial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(null=True)),
                ("node", models.CharField(max_length=255)),
                ("serial", models.PositiveBigIntegerField(null=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="desecapi.domain",
                    ),
                ),
            ],
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("DomainSerial"),
                models.Model,
            ),
        ),
        migrations.AddConstraint(
            model_name="domainserial",
            constraint=models.UniqueConstraint(
                fields=("domain", "node", "updated", "serial"),
                name="domain_serial_unique_policy",
                nulls_distinct=False,
            ),
        ),
    ]
