# Generated by Django 5.1.3 on 2024-11-21 15:45

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desecapi", "0039_token_perm_create_domain_token_perm_delete_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="auto_policy",
            field=models.BooleanField(default=False),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="token",
            trigger=pgtrigger.compiler.Trigger(
                name="token_auto_policy",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    constraint="CONSTRAINT",
                    func="\n                    IF\n                        NEW.auto_policy = true AND NOT EXISTS(\n                            SELECT * FROM desecapi_tokendomainpolicy WHERE token_id = NEW.id AND domain_id IS NULL AND subname IS NULL AND type IS NULL\n                        )\n                    THEN\n                        RAISE EXCEPTION 'Token auto policy without a default policy is not allowed. (token.id=%s)', NEW.id;\n                    END IF;\n                    RETURN NULL;\n                ",
                    hash="f2cc6e70892817e04cbfbbff63bd4ddbe05b9aa5",
                    operation="UPDATE OR INSERT",
                    pgid="pgtrigger_token_auto_policy_8e6d9",
                    table="desecapi_token",
                    timing="DEFERRABLE INITIALLY DEFERRED",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="tokendomainpolicy",
            trigger=pgtrigger.compiler.Trigger(
                name="default_policy_when_auto_policy",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n                    IF\n                        OLD.domain_id IS NULL AND OLD.subname IS NULL AND OLD.type IS NULL AND (SELECT auto_policy FROM desecapi_token WHERE id = OLD.token_id) = true\n                    THEN\n                        RAISE EXCEPTION 'Cannot delete default policy while auto_policy is in effect. (tokendomainpolicy.id=%s)', OLD.id;\n                    END IF;\n                    RETURN OLD;\n                ",
                    hash="3d55e73e6ae7d089b5ff136ac16f0c2675285bf2",
                    operation="DELETE",
                    pgid="pgtrigger_default_policy_when_auto_policy_a1fd2",
                    table="desecapi_tokendomainpolicy",
                    when="BEFORE",
                ),
            ),
        ),
    ]
