# Generated by Django 5.1.4 on 2024-12-17 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desecapi", "0042_rename_user_token_owner_token_user_override_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthenticatedActivateUserWithOverrideTokenAction",
            fields=[
                (
                    "authenticateduseraction_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="desecapi.authenticateduseraction",
                    ),
                ),
                ("outreach_preference", models.BooleanField(default=True)),
            ],
            options={
                "managed": False,
            },
            bases=("desecapi.authenticateduseraction",),
        ),
    ]
