# Generated by Django 5.2.10 on 2026-01-12 23:43

import django.contrib.postgres.constraints
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("desecapi", "0044_alter_captcha_created_alter_domain_renewal_state_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="rr",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[("rrset", "="), ("content", "=")],
                name="unique_record_in_rrset",
            ),
        ),
    ]
