# Generated by Django 5.1.8 on 2025-04-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desecapi", "0044_alter_captcha_created_alter_domain_renewal_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="delegation_status",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Not Delegated"),
                    (1, "Elsewhere"),
                    (2, "Partial"),
                    (3, "Exclusive"),
                    (4, "Multi"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="delegation_status_touched",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="domain",
            name="security_status",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Insecure"),
                    (1, "Bogus"),
                    (2, "Secure Exclusive"),
                    (3, "Secure"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="security_status_touched",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
