# Generated by Django 5.2.10 on 2026-02-10 00:00

from django.conf import settings
from django.db import migrations, models


def set_allow_local_ns_changes(apps, schema_editor):
    Domain = apps.get_model("desecapi", "Domain")
    Domain.objects.update(allow_local_ns_changes=True)

    local_suffixes = set(settings.LOCAL_PUBLIC_SUFFIXES)
    if not local_suffixes:
        return

    to_update = []
    for domain in Domain.objects.only("id", "name").iterator():
        parent = domain.name.partition(".")[2] or None
        if parent in local_suffixes:
            to_update.append(domain.id)

    if to_update:
        Domain.objects.filter(id__in=to_update).update(allow_local_ns_changes=False)


class Migration(migrations.Migration):
    dependencies = [
        ("desecapi", "0045_rr_unique_record_in_rrset"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="allow_local_ns_changes",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(set_allow_local_ns_changes, migrations.RunPython.noop),
    ]
