# Generated by Django 5.2.10 on 2026-02-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desecapi", "0045_rr_unique_record_in_rrset"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="nslord",
            field=models.CharField(
                choices=[("pdns", "powerdns"), ("knot", "knotdns")],
                default="pdns",
                max_length=16,
            ),
        ),
    ]
