# Generated by Django 6.0.8 on 2026-08-20 12:00

from django.conf import settings
from django.db import migrations, models

import desecapi.models.domains


def clamp_minimum_ttl(apps, schema_editor):
    # The minimum TTL used to double as the default TTL, so deployments tended to
    # configure it higher than actually needed. Now that the default TTL is a
    # separate setting, converge existing domains on the configured minimum.
    # Domains with an individually lowered minimum are left alone.
    Domain = apps.get_model("desecapi", "Domain")
    Domain.objects.filter(minimum_ttl__gt=settings.MINIMUM_TTL_DEFAULT).update(
        minimum_ttl=settings.MINIMUM_TTL_DEFAULT
    )


class Migration(migrations.Migration):
    dependencies = [
        (
            "desecapi",
            "0045_rr_unique_record_in_rrset_squashed_0046_remove_rr_unique_record_in_rrset_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="default_ttl",
            field=models.PositiveIntegerField(
                default=desecapi.models.domains.Domain._default_ttl_default
            ),
        ),
        migrations.RunPython(clamp_minimum_ttl, migrations.RunPython.noop),
    ]
