# Generated by Django 5.2.17 on 2026-08-13 01:50

import django.contrib.postgres.fields
import django.db.models.deletion
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "desecapi",
            "0045_rr_unique_record_in_rrset_squashed_0046_remove_rr_unique_record_in_rrset_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DelegationCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("checked", models.DateTimeField(auto_now=True)),
                (
                    "security_status",
                    models.IntegerField(
                        choices=[
                            (0, "Secure"),
                            (1, "Insecure"),
                            (2, "Misconfigured"),
                            (3, "Error"),
                        ]
                    ),
                ),
                (
                    "nameserver_status",
                    models.IntegerField(
                        choices=[
                            (0, "Correctly Delegated"),
                            (1, "Multi Provider"),
                            (2, "Other Provider"),
                            (3, "Not Delegated"),
                            (4, "Error"),
                        ]
                    ),
                ),
                (
                    "nameservers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        default=list,
                        size=None,
                    ),
                ),
                ("ede_code", models.PositiveSmallIntegerField(null=True)),
                ("ede_text", models.TextField(blank=True)),
                ("rcode", models.PositiveSmallIntegerField(null=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegation_checks",
                        to="desecapi.domain",
                    ),
                ),
            ],
            options={
                "ordering": ("created",),
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("DelegationCheck"),
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="current_delegation_check",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="desecapi.delegationcheck",
            ),
        ),
    ]
