CREATE DATABASE desec;
CREATE USER desec IDENTIFIED BY 'test123';
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, INDEX, CREATE, ALTER, DROP ON desec.* TO desec;

CREATE DATABASE pdnslord;
CREATE USER pdnslord IDENTIFIED BY '123test';
GRANT SELECT, INSERT, UPDATE, DELETE ON pdnslord.* TO pdnslord;

CREATE USER poweradmin IDENTIFIED BY '123passphrase';
GRANT SELECT, INSERT, UPDATE, DELETE ON pdnslord.* TO poweradmin;

