<script>
import CrudList from './CrudList';

export default {
  name: 'TLSIdentityList',
  extends: CrudList,
  components: {
  },
  data() {
    return {
        createable: true,
        updatable: false,
        destroyable: true,
        headlines: {
          table: 'TLS Server Identities',
          create: 'Add an identity',
          destroy: 'Remove an identity',
        },
        texts: {
          banner: () => 'Publish your TLS servers\' cryptographic identity in the DNS by adding your server certificate(s) below.',
          create: () => `Adds a TLS identity.`,
          destroy: d => (`Remove TLS identity ${d.name}?`),
          destroyInfo: () => 'Removing this TLS identity may render your website unavailable users.',
        },
        columns: {
          name: {
            name: 'item.name',
            text: 'Name',
            textCreate: 'Enter identity name',
            align: 'left',
            sortable: true,
            value: 'name',
            readonly: true,
            required: false,
            writeOnCreate: true,
            datatype: 'GenericText',
            searchable: true,
          },
          cert: {
            name: 'item.certificate',
            text: 'Certificate',
            textCreate: 'Paste certificte in PEM format',
            align: 'left',
            sortable: true,
            value: 'certificate',
            readonly: true,
            required: true,
            writeOnCreate: true,
            datatype: 'MultilineText',
            searchable: false,
          },
          // fingerprint: {
          //   name: 'item.fingerprint',
          //   text: 'Fingerprint',
          //   algin: 'left',
          //   sortable: true,
          //   value: 'fingerprint',
          //   readonly: true,
          //   datatype: 'GenericText',
          // },
          // not_valid_before: {
          //   name: 'item.not_valid_before',
          //   text: 'Begin Validity',
          //   algin: 'left',
          //   sortable: true,
          //   value: 'not_valid_before',
          //   readonly: true,
          //   datatype: 'TimeAgo',
          // },
          // not_valid_after: {
          //   name: 'item.not_valid_after',
          //   text: 'Expiration',
          //   algin: 'left',
          //   sortable: true,
          //   value: 'not_valid_after',
          //   readonly: true,
          //   datatype: 'TimeAgo',
          // },
          // subject_names: {
          //   name: 'item.subject_names',
          //   text: 'Subject Names',
          //   algin: 'left',
          //   sortable: true,
          //   value: 'subject_names',
          //   readonly: true,
          //   datatype: 'MultilineText',
          // },
          // published_at: {
          //   name: 'item.published_at',
          //   text: 'published at',
          //   algin: 'left',
          //   sortable: true,
          //   value: 'published_at',
          //   readonly: true,
          //   datatype: 'MultilineText',
          // },
          domains: {
            name: 'item.domains',
            text: 'domains',
            algin: 'left',
            sortable: true,
            value: 'domains',
            readonly: true,
            datatype: 'DomainList',
          },
          tlsa_selector: {
            name: 'item.tlsa_selector',
            text: 'TLSA Selector',
            algin: 'left',
            sortable: true,
            value: 'tlsa_selector',
            readonly: true,
            writeOnCreate: true,
            datatype: 'GenericText',
          },
          tlsa_matching_type: {
            name: 'item.tlsa_matching_type',
            text: 'TLSA Matching Type',
            algin: 'left',
            sortable: true,
            value: 'tlsa_matching_type',
            readonly: true,
            writeOnCreate: true,
            datatype: 'GenericText',
          },
          tlsa_certificate_usage: {
            name: 'item.tlsa_certificate_usage',
            text: 'TLSA Certificate Usage',
            algin: 'left',
            sortable: true,
            value: 'tlsa_certificate_usage',
            readonly: true,
            writeOnCreate: true,
            datatype: 'GenericText',
          },
          protocol: {
            name: 'item.protocol',
            text: 'Protocol',
            algin: 'left',
            sortable: true,
            value: 'protocol',
            readonly: true,
            writeOnCreate: true,
            datatype: 'GenericText',
          },
          port: {
            name: 'item.port',
            text: 'Port',
            algin: 'left',
            sortable: true,
            value: 'port',
            readonly: true,
            writeOnCreate: true,
            datatype: 'GenericText',
          },

          scheduled_removal: {
            name: 'item.scheduled_removal',
            text: 'Scheduled Removal',
            align: 'left',
            sortable: true,
            value: 'scheduled_removal',
            readonly: true,
            datatype: 'TimeAgo',
            searchable: false,
          },
          created: {
            name: 'item.created',
            text: 'Created',
            align: 'left',
            sortable: true,
            value: 'created',
            readonly: true,
            datatype: 'TimeAgo',
            searchable: false,
          },
        },
        actions: [
          // {
          //   key: 'info',
          //   go: d => this.showDomainInfo(d),
          //   icon: 'mdi-information',
          // },
        ],
        paths: {
          list: 'identities/tls/',
          create: 'identities/tls/',
          delete: 'identities/tls/:{id}',
        },
        expandable: true,
        expandComponentName: "TLSAIdentity",
        itemDefaults: () => ({ name: '' }),
        handleRowClick: (value) => {
          console.log(value);
          // this.$router.push({name: 'domain', params: {domain: value.name}});
        },
    }
  },
  computed: {
  },
};
</script>
