target-version = "py313"

[lint]
select = ["E4", "E7", "E9", "F", "UP", "I", "B"]
ignore = ["B904"]  # raise ... from ...

[lint.per-file-ignores]
"**/__init__.py" = ["F401", "F403"]  # re-exports
"api/settings_quick_test.py" = ["F403", "F405"]  # settings are star-imported
"desecapi/migrations/*" = ["ALL"]  # generated
