#!/usr/bin/env bash
set -e

# wait for api database to come up
until PGPASSWORD=$DESECSTACK_DBAPI_PASSWORD_desec psql -h dbapi -U desec -c '\q'; do
  >&2 echo "Postgres is unavailable - sleeping"
  sleep 1
done

# wait for pdns api to come up
host=nslord; port=8081; n=120; i=0; while ! (echo > /dev/tcp/$host/$port) 2> /dev/null; do [[ $i -eq $n ]] && >&2 echo "$host:$port not up after $n seconds, exiting" && exit 1; echo "waiting for $host:$port to come up"; sleep 1; i=$((i+1)); done
host=nsmaster; port=8081; n=120; i=0; while ! (echo > /dev/tcp/$host/$port) 2> /dev/null; do [[ $i -eq $n ]] && >&2 echo "$host:$port not up after $n seconds, exiting" && exit 1; echo "waiting for $host:$port to come up"; sleep 1; i=$((i+1)); done
