#!/usr/bin/env bash
set -e

# wait for api database to come up
until PGPASSWORD=$DESECSTACK_DBAPI_PASSWORD_desec psql -h dbapi -U desec -c '\q'; do
  >&2 echo "Postgres is unavailable - sleeping"
  sleep 1
done
